services:
  - type: web
    name: portfolio-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /api/health